// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';

export function GetWithHeaders(arg1:network.HttpRequest):Promise<network.HttpResponse>;
