name: Http UI CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Use Node.js 20"
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: "Use Go 1.21"
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build and Test frontend
        run: |
          npm --prefix frontend ci
          npm --prefix frontend run build
          npm --prefix frontend test
